#!/bin/bash

set -e

echo "==> Installing required libraries…"

if [ "$(uname)" == "Darwin" ]; then
  for pkg in flex bison; do
    if brew list -1 | grep -q "^${pkg}\$"; then
        echo "Package '$pkg' is installed"
    else
        echo "Package '$pkg' is not installed"
        brew install $pkg
    fi
  done
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sudo apt-get -qq -y install flex bison
fi

if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]
then
    echo 'yes' | sudo add-apt-repository ppa:kalakris/cmake
    sudo apt-get update -qq
    sudo apt-get install -qq cmake python3 valgrind
elif [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]
then
    echo "Building without python3, to make sure that works."
fi
