#!/bin/bash

set -e

echo "==> Installing required libraries…"

if [ "$(uname)" == "Darwin" ]; then
  for pkg in flex bison cmake valgrind; do
    if brew list -1 | grep -q "^${pkg}\$"; then
        echo "Package '$pkg' is installed"
    else
        echo "Package '$pkg' is not installed"
        brew install $pkg
    fi
  done
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  if [ -z "$TRAVIS" ]; then
    sudo apt-get -qq -y install flex bison cmake valgrind
  else
    echo "Packages already installed on Travis CI."
  fi
fi

mkdir -p build
