#!/usr/bin/env ruby
# frozen_string_literal: true

require "octokit"

%x(git push origin)

%x(rm -rf build)
%x(mkdir build)

Dir.chdir("build") do
  %x(cmake ..)
  %x(make)
end

MTEX2MML_HEADER = File.read(File.join("src", "mtex2MML.h"))
VERSION = MTEX2MML_HEADER.match(/MTEX2MML_VERSION\s*"(.+?)"/)[1]
TAG_NAME = "v#{VERSION}"

puts "Creating tag #{TAG_NAME}..."
%x(git tag #{TAG_NAME})

puts "Creating release..."
client = Octokit::Client.new(access_token: ENV["GITHUB_TOKEN"])
_release_response = client.create_release("gjtorikian/mtex2MML", TAG_NAME, \
  name: VERSION)

puts "Done!"
