#!/usr/bin/env ruby

require 'octokit'

`git push origin`

`rm -rf build`
`mkdir build`

Dir.chdir 'build' do
  `cmake ..`
  `make`
end

MTEX2MML_HEADER = File.read(File.join('src', 'mtex2MML.h'))
VERSION = MTEX2MML_HEADER.match(/MTEX2MML_VERSION\s*"(.+?)"/)[1]
TAG_NAME = "v#{VERSION}"

puts "Creating tag #{TAG_NAME}..."
`git tag #{TAG_NAME}`

puts 'Creating release...'
client = Octokit::Client.new(:access_token => ENV['GITHUB_TOKEN'])
release_response = client.create_release 'gjtorikian/mtex2MML', TAG_NAME, \
                                        :name => VERSION

puts 'Done!'
