#!/bin/bash

set -e

echo 'inline'
echo '\sin y'     | ./mtex2MML --inline | grep "display='inline'" || exit 1
echo ''

echo 'display'
echo '\sin y'     | ./mtex2MML --display | grep "display='block'" || exit 1
echo ''

echo 'inline print-mtex'
echo '\sin y'     | ./mtex2MML --inline --print-mtex | grep '$\\sin y\$'|| exit 1
echo ''

echo 'display print-mtex'
echo '\sin y'     | ./mtex2MML --display --print-mtex | grep '$$\\sin y\$\$' || exit 1
echo ''

echo 'dollar'
echo '$\sin y$'   | ./mtex2MML | grep "display='inline'" || exit 1

echo 'double dollar'
echo '$$\sin y$$' | ./mtex2MML | grep "display='block'" || exit 1

echo 'parens'
echo '\(\sin y\)' | ./mtex2MML | grep "display='inline'" || exit 1

echo 'brackets'
echo '\[\sin y\]' | ./mtex2MML | grep "display='block'" || exit 1

echo 'dollar use-dollar'
echo '$\sin y$'   | ./mtex2MML --use-dollar | grep "display='inline'" || exit 1

echo 'double dollar use-double'
echo '$$\sin y$$' | ./mtex2MML --use-double | grep "display='block'" || exit 1

echo 'parens use-parens'
echo '\(\sin y\)' | ./mtex2MML --use-parens | grep "display='inline'" || exit 1

echo 'brackets use-brackets'
echo '\[\sin y\]' | ./mtex2MML --use-brackets | grep "display='block'" || exit 1

echo 'env use-env'
echo '\\begin{align}3x + 9y &=  -12\\end{align}' | ./mtex2MML --use-env | grep "display='block'" || exit 1

echo 'DONE with command check'
